version: 1.0.{build}
os: Visual Studio 2017
platform: x64
clone_folder: C:\projects\wildmeshing
shallow_clone: true
branches:
  only:
    - master
environment:
  APPVEYOR_RDP_PASSWORD: wmsh.paAss126.
  matrix:
  - config: Debug
    PYTHON: "C:\\Python36-x64"
    PYTHON_VERSION: "3.6" # currently 3.6.8
    PYTHON_ARCH: "64"
    MINICONDA: C:\Miniconda3-x64

  - config: Debug
    PYTHON: "C:\\Python35-x64"
    PYTHON_VERSION: "3.5" # currently 3.5.8
    PYTHON_ARCH: "64"
    MINICONDA: C:\Miniconda3-x64
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# install:
#   # - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\include;%MINICONDA%\\Library\\lib;%MINICONDA%\\Library\\bin;%PATH%"
#   - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
#   - "conda create -q -n wildmeshing python=%PYTHON_VERSION% -y"
#   - "activate wildmeshing"
#   - "python --version"
#   - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
#   - "conda install numpy -y"
#   - "conda install -c conda-forge mpir -y"
#   - "conda install -c conda-forge svgwrite -y"
#   - "python -c \"import numpy as np;import sys;print(np.get_include())\""
build:
  parallel: true
build_script:
  # - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\include;%MINICONDA%\\Library\\lib;%MINICONDA%\\Library\\bin;%PATH%"
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "conda create -q -n wildmeshing python=%PYTHON_VERSION% -y"
  - "activate wildmeshing"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "conda install numpy -y"
  - "conda install -c conda-forge mpir -y"
  - "conda install -c conda-forge svgwrite -y"
  - "python -c \"import numpy as np;import sys;print(np.get_include())\""
  - cd c:\projects\wildmeshing
  - "python --version"
  - python setup.py build --debug install
#
# test_script:
  # - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  # - "activate wildmeshing"
  - cd c:\projects\wildmeshing
  - "python --version"
  - python test/tri_test.py
  - python test/tet_test.py