version: 1.0.{build}
os: Visual Studio 2017
platform: x64
clone_folder: C:\projects\wildmeshing
shallow_clone: true
branches:
  only:
    - master
environment:
  APPVEYOR_RDP_PASSWORD: wmsh.paAss126.
  matrix:
  - config: Release
    PYTHON: "C:\\Python36-x64"
    PYTHON_VERSION: "3.6" # currently 3.6.8
    PYTHON_ARCH: "64"
    MINICONDA: C:\Miniconda3

  - config: Release
    PYTHON: "C:\\Python35-x64"
    PYTHON_VERSION: "3.5" # currently 3.5.8
    PYTHON_ARCH: "64"
    MINICONDA: C:\Miniconda3
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "conda create --name wildmeshing python=%PYTHON_VERSION% -y"
  - "conda activate wildmeshing"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "conda install numpy -y"
  - "python -c \"import numpy as np;import sys;print(np.get_include())\""
  - "conda install -c conda-forge r-gmp -y"
build:
  parallel: true
build_script:
  - "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "conda activate wildmeshing"
  - cd c:\projects\wildmeshing
  - "python --version"
  - python setup.py build --debug install

test_script:
  - cd c:\projects\wildmeshing
  - python test/tri_test.py
  - python test/tet_test.py