language: python
python:
  - "3.5"
  - "3.6"
os:
  - linux
  # - osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - libgmp3-dev
env:
  - CC=gcc-7 && CXX=g++-7
install:
  - pip install numpy
script:
  - python -m pip install . -vv
  - ls ./
  - ls 3rdparty
  - ls 3rdparty\data
  - python test/tri_test.py
  - python test/tet_test.py